server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    #  RUTA PRINCIPAL SPA (Angular)
    location / {
        try_files $uri $uri/ /index.html;
    }

    #  PROXY PARA API DJANGO
    location /api/ {
        proxy_pass http://172.31.88.123:8000/;  #  IP PRIVADA DEL BACKEND DJANGO EN AWS

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        #  CORS
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS, DELETE, PUT, PATCH';
        add_header Access-Control-Allow-Headers 'Origin, Content-Type, Accept, Authorization';

        #  OPCIONES PARA PREFLIGHT (CORS)
        if ($request_method = OPTIONS) {
            add_header Content-Length 0;
            add_header Content-Type text/plain;
            return 204;
        }
    }
}